#include <ESP8266WiFi.h>
#include <ESP8266HTTPClient.h>
#include "DHT.h"
#include <String.h>
#include <ArduinoJson.h>
//#include <SSLClient.h>
//#include <functional-vlpp.h>
//#include <EthernetWebServer_SSL.h>

const char* ssid     = "ssid"; //Set Wifi SSID
const char* password = "password";//Set Wifi password


const char* host = "host";

const int buzzer1 =  D1;
const int buzzer2 =  D2;
const int LED1 =  D0;  // เชื่อมต่อ Wifi ได้
const int LED2 =  D3;  // แจ้งเตือน มีปัญหา
const int LED3 =  D4;  // ไม่มาสามารถ Ping เน็ตได้
WiFiClient  client;

int id,temp,humidity,date = 0;

void setup()
{
  Serial.begin(115200);

   WiFi.begin(ssid, password);
  //Set WiFi mode
  //You can choose between WIFI_AP, WIFI_STA, WIFI_AP_STA or WIFI_OFF
  WiFi.mode(WIFI_STA);
  while (WiFi.status() != WL_CONNECTED)
     delay(500);
  {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  digitalWrite(LED1, HIGH);
  Serial.println(WiFi.localIP());
//  ThingSpeak.begin(client);
  
  pinMode(buzzer1, OUTPUT);
  pinMode(buzzer2, OUTPUT);
  
  pinMode(LED1, OUTPUT); // กำหนดขาทำหน้าที่ให้ขา D0 เป็น OUTPUT 
  pinMode(LED2, OUTPUT); // กำหนดขาทำหน้าที่ให้ขา D3 เป็น OUTPUT 
  pinMode(LED3, OUTPUT); // กำหนดขาทำหน้าที่ให้ขา D4 เป็น OUTPUT 

//int value = 0;
}
int value = 0;



void loop() {
  delay(500);
  ++value;
  Serial.print("connecting to ");
  Serial.println(host);

  WiFiClient client;

  const int httpPort = 80;
  //const int httpPort = 443;
  if (!client.connect(host, httpPort)) {
  //if (!client.connectSSL(host, httpPort)) {
    Serial.println("connection failed");
    digitalWrite(LED3, HIGH);
    delay(300);
    digitalWrite(LED3, LOW);
    delay(300);
    digitalWrite(LED3, HIGH);
    delay(300);
    digitalWrite(LED3, LOW);
    return;
  }


    String url = "http://localhost/iot/last_temp_json.php";    //ดึงค่าจากไฟล์ http://9arduino.nisit.net/api/json.php

  Serial.print("Requesting URL: ");
  Serial.println(url);

  client.print(String("GET ") + url + " HTTP/1.1\r\n" +
              "Host: " + host + "\r\n" + 
              "Connection: close\r\n\r\n");
  unsigned long timeout = millis();
  while (client.available() == 0) {
    if (millis() - timeout > 5000) {
      Serial.println(">>> Client Timeout !");
      client.stop();
      return;
    }
  }

// ในส่วนของการดึง Json โดยการดึง ตัวแปรที่ชื่อว่าตัวแปรมาใช้งาน
// ยกตัวอย่าง ตัวแปร id ค่าที่ได้จะเป็น 1 แสดงออกมา เราสามารถนำ ตัว แปร id ไปใช้งานต่างๆได้เช่นการแสดงข้อความออกจอ LCD เปิดปิดไฟตามกำหนด

  if(client.find("")){
      client.find("id");  // 
      id = client.parseFloat();
      client.find("temp");
      temp = client.parseFloat();
      client.find("humidity");
      humidity = client.parseFloat();
      client.find("date");
      date = client.parseFloat();
  }
  Serial.print("Output = ");
  Serial.println(id); 
  Serial.print("Output = ");
  Serial.println(temp); 
  if (temp >=28){
  Serial.println("ห้อง Server ร้อน แล้ว");
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
     digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
     digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
  }else{
    Serial.println("OK ปกติ");
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    }
  Serial.print("Output = ");
  Serial.println(humidity); 
  if (humidity >=65){
  Serial.println("ห้อง Server ความชื้นเกิน แล้ว");
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
     digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
     digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    digitalWrite(buzzer1, LOW);
    digitalWrite(buzzer2, LOW);
    digitalWrite(LED2, HIGH);
    delay(200);
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
  }else{
    Serial.println("OK ปกติ");
    digitalWrite(buzzer1, HIGH);
    digitalWrite(buzzer2, HIGH);
    digitalWrite(LED2, LOW);
    delay(200);
    }
  Serial.print("Output = ");
  Serial.println(date); 
  Serial.print("Output = ");    
  Serial.println();
  Serial.println("closing connection");

//  delay(5000);// = 5 วิ
//  delay(10000);// = 10 วิ
//  delay(60000);// = 1 นาที
//  delay(120000);// = 2 นาที
    delay(180000);// = 3 นาที
//  delay(300000);// = 5 นาที
//  delay(900000);// = 15 นาที
//  delay(1800000);// = 30 นาที
  
}
